# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creationUe.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(341, 360)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 361))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.couLabel = QtGui.QLabel(self.layoutWidget)
        self.couLabel.setObjectName(_fromUtf8("couLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.couLabel)
        self.codeUe = QtGui.QLineEdit(self.layoutWidget)
        self.codeUe.setObjectName(_fromUtf8("codeUe"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.codeUe)
        self.ssLabel = QtGui.QLabel(self.layoutWidget)
        self.ssLabel.setObjectName(_fromUtf8("ssLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ssLabel)
        self.nomUe = QtGui.QLineEdit(self.layoutWidget)
        self.nomUe.setObjectName(_fromUtf8("nomUe"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nomUe)
        self.responsableLabel = QtGui.QLabel(self.layoutWidget)
        self.responsableLabel.setObjectName(_fromUtf8("responsableLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.responsableLabel)
        self.responsableUe = QtGui.QComboBox(self.layoutWidget)
        self.responsableUe.setInsertPolicy(QtGui.QComboBox.InsertAtCurrent)
        self.responsableUe.setIconSize(QtCore.QSize(16, 16))
        self.responsableUe.setObjectName(_fromUtf8("responsableUe"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.responsableUe)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.onglets = QtGui.QTabWidget(self.layoutWidget)
        self.onglets.setObjectName(_fromUtf8("onglets"))
        self.CMs = QtGui.QWidget()
        self.CMs.setObjectName(_fromUtf8("CMs"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.CMs)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(60, 50, 221, 81))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.nombreDeTdsLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.nombreDeTdsLabel.setObjectName(_fromUtf8("nombreDeTdsLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel)
        self.nbCM = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.nbCM.setObjectName(_fromUtf8("nbCM"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.nbCM)
        self.nombreDeTdsLabel_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.nombreDeTdsLabel_2.setObjectName(_fromUtf8("nombreDeTdsLabel_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel_2)
        self.dureeCM = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.dureeCM.setObjectName(_fromUtf8("dureeCM"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.dureeCM)
        self.onglets.addTab(self.CMs, _fromUtf8(""))
        self.TDs = QtGui.QWidget()
        self.TDs.setObjectName(_fromUtf8("TDs"))
        self.formLayoutWidget_7 = QtGui.QWidget(self.TDs)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(60, 60, 223, 71))
        self.formLayoutWidget_7.setObjectName(_fromUtf8("formLayoutWidget_7"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.nombreDeTdsLabel_3 = QtGui.QLabel(self.formLayoutWidget_7)
        self.nombreDeTdsLabel_3.setObjectName(_fromUtf8("nombreDeTdsLabel_3"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel_3)
        self.nbTD = QtGui.QSpinBox(self.formLayoutWidget_7)
        self.nbTD.setObjectName(_fromUtf8("nbTD"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.nbTD)
        self.nombreDeTdsLabel_4 = QtGui.QLabel(self.formLayoutWidget_7)
        self.nombreDeTdsLabel_4.setObjectName(_fromUtf8("nombreDeTdsLabel_4"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel_4)
        self.dureeTD = QtGui.QSpinBox(self.formLayoutWidget_7)
        self.dureeTD.setObjectName(_fromUtf8("dureeTD"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.dureeTD)
        self.onglets.addTab(self.TDs, _fromUtf8(""))
        self.TPs = QtGui.QWidget()
        self.TPs.setObjectName(_fromUtf8("TPs"))
        self.formLayoutWidget_8 = QtGui.QWidget(self.TPs)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(60, 60, 223, 71))
        self.formLayoutWidget_8.setObjectName(_fromUtf8("formLayoutWidget_8"))
        self.formLayout_8 = QtGui.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.nombreDeTdsLabel_5 = QtGui.QLabel(self.formLayoutWidget_8)
        self.nombreDeTdsLabel_5.setObjectName(_fromUtf8("nombreDeTdsLabel_5"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel_5)
        self.nbTP = QtGui.QSpinBox(self.formLayoutWidget_8)
        self.nbTP.setObjectName(_fromUtf8("nbTP"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.nbTP)
        self.nombreDeTdsLabel_6 = QtGui.QLabel(self.formLayoutWidget_8)
        self.nombreDeTdsLabel_6.setObjectName(_fromUtf8("nombreDeTdsLabel_6"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel_6)
        self.dureeTP = QtGui.QSpinBox(self.formLayoutWidget_8)
        self.dureeTP.setObjectName(_fromUtf8("dureeTP"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.dureeTP)
        self.onglets.addTab(self.TPs, _fromUtf8(""))
        self.Examens = QtGui.QWidget()
        self.Examens.setObjectName(_fromUtf8("Examens"))
        self.formLayoutWidget_9 = QtGui.QWidget(self.Examens)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(60, 60, 223, 71))
        self.formLayoutWidget_9.setObjectName(_fromUtf8("formLayoutWidget_9"))
        self.formLayout_9 = QtGui.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.nombreDeTdsLabel_7 = QtGui.QLabel(self.formLayoutWidget_9)
        self.nombreDeTdsLabel_7.setObjectName(_fromUtf8("nombreDeTdsLabel_7"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel_7)
        self.nbExamen = QtGui.QSpinBox(self.formLayoutWidget_9)
        self.nbExamen.setObjectName(_fromUtf8("nbExamen"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.nbExamen)
        self.nombreDeTdsLabel_8 = QtGui.QLabel(self.formLayoutWidget_9)
        self.nombreDeTdsLabel_8.setObjectName(_fromUtf8("nombreDeTdsLabel_8"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel_8)
        self.dureeExamen = QtGui.QSpinBox(self.formLayoutWidget_9)
        self.dureeExamen.setObjectName(_fromUtf8("dureeExamen"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.dureeExamen)
        self.onglets.addTab(self.Examens, _fromUtf8(""))
        self.Autres = QtGui.QWidget()
        self.Autres.setObjectName(_fromUtf8("Autres"))
        self.formLayoutWidget_10 = QtGui.QWidget(self.Autres)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(70, 70, 191, 61))
        self.formLayoutWidget_10.setObjectName(_fromUtf8("formLayoutWidget_10"))
        self.formLayout_10 = QtGui.QFormLayout(self.formLayoutWidget_10)
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.nombreDeTdsLabel_9 = QtGui.QLabel(self.formLayoutWidget_10)
        self.nombreDeTdsLabel_9.setObjectName(_fromUtf8("nombreDeTdsLabel_9"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.nombreDeTdsLabel_9)
        self.nbAutre = QtGui.QSpinBox(self.formLayoutWidget_10)
        self.nbAutre.setObjectName(_fromUtf8("nbAutre"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.nbAutre)
        self.onglets.addTab(self.Autres, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.onglets)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.annulerUe = QtGui.QPushButton(self.layoutWidget)
        self.annulerUe.setObjectName(_fromUtf8("annulerUe"))
        self.horizontalLayout_3.addWidget(self.annulerUe)
        self.ajouterUe = QtGui.QPushButton(self.layoutWidget)
        self.ajouterUe.setObjectName(_fromUtf8("ajouterUe"))
        self.horizontalLayout_3.addWidget(self.ajouterUe)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        self.responsableUe.setCurrentIndex(-1)
        self.onglets.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.couLabel.setText(_translate("Dialog", "Code Ue", None))
        self.ssLabel.setText(_translate("Dialog", "Nom Ue", None))
        self.responsableLabel.setText(_translate("Dialog", "Responsable", None))
        self.nombreDeTdsLabel.setText(_translate("Dialog", "Nombre de CMs", None))
        self.nombreDeTdsLabel_2.setText(_translate("Dialog", "Durée de CMs", None))
        self.onglets.setTabText(self.onglets.indexOf(self.CMs), _translate("Dialog", "CMs", None))
        self.nombreDeTdsLabel_3.setText(_translate("Dialog", "Nombre de TDs", None))
        self.nombreDeTdsLabel_4.setText(_translate("Dialog", "Durée de TDs", None))
        self.onglets.setTabText(self.onglets.indexOf(self.TDs), _translate("Dialog", "TDs", None))
        self.nombreDeTdsLabel_5.setText(_translate("Dialog", "Nombre de TPs", None))
        self.nombreDeTdsLabel_6.setText(_translate("Dialog", "Durée de TPs", None))
        self.onglets.setTabText(self.onglets.indexOf(self.TPs), _translate("Dialog", "TPs", None))
        self.nombreDeTdsLabel_7.setText(_translate("Dialog", "Nombre d\'examens", None))
        self.nombreDeTdsLabel_8.setText(_translate("Dialog", "Durée d\'examens", None))
        self.onglets.setTabText(self.onglets.indexOf(self.Examens), _translate("Dialog", "Examens", None))
        self.nombreDeTdsLabel_9.setText(_translate("Dialog", "Nombre d\'autres", None))
        self.onglets.setTabText(self.onglets.indexOf(self.Autres), _translate("Dialog", "Autres", None))
        self.annulerUe.setText(_translate("Dialog", "Annuler", None))
        self.ajouterUe.setText(_translate("Dialog", "Ajouter", None))
